name: Snapshot Release

on:
  push:
    branches: [ main ]

jobs:
  snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Package
        id: package
        run: $MVN package -P prod
      - name: Set up Maven Settings
        id: setup-maven-settings
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: Deploy
        id: deploy
        run: $MVN deploy -P prod
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: Login to Quay.io
        id: login-to-quay-io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Standalone Latest
        id: standalone-latest
        run: $MVN package --projects standalone --also-make -P native,prod,theme-hal -Dquarkus.native.remote-container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.image=quay.io/halconsole/hal-development:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
